// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx7k4y4vyMi49wKcRj37rIUU_tggdbC4Q',
    appId: '1:1068901468204:web:9206abe0e9bc4a4312e989',
    messagingSenderId: '1068901468204',
    projectId: 'dplus-f473b',
    authDomain: 'dplus-f473b.firebaseapp.com',
    storageBucket: 'dplus-f473b.appspot.com',
    measurementId: 'G-D9H8BC0602',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu4lsJZECzsojY9kFAyCUaT7dKzrOF-1I',
    appId: '1:1068901468204:android:8396546fa6bd70f212e989',
    messagingSenderId: '1068901468204',
    projectId: 'dplus-f473b',
    storageBucket: 'dplus-f473b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaA2E82WEaK5ODmLA-s9KEWlz7WseBfwQ',
    appId: '1:1068901468204:ios:3fadfd49a1912b7012e989',
    messagingSenderId: '1068901468204',
    projectId: 'dplus-f473b',
    storageBucket: 'dplus-f473b.appspot.com',
    androidClientId: '1068901468204-ksn9j01pogduk6r9tfv4a7cs1q3jo8vq.apps.googleusercontent.com',
    iosClientId: '1068901468204-hlehc8d4helqhotan6qi783mofun4v5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.dplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaA2E82WEaK5ODmLA-s9KEWlz7WseBfwQ',
    appId: '1:1068901468204:ios:a73448dae376d5fe12e989',
    messagingSenderId: '1068901468204',
    projectId: 'dplus-f473b',
    storageBucket: 'dplus-f473b.appspot.com',
    androidClientId: '1068901468204-ksn9j01pogduk6r9tfv4a7cs1q3jo8vq.apps.googleusercontent.com',
    iosClientId: '1068901468204-dlpnq0pg7vq4ng35qtusb52ci0tjf5g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dplus.RunnerTests',
  );
}
